# Generated by Django 3.2.5 on 2021-07-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
