# Generated by Django 3.2.5 on 2021-07-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20210725_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('number', models.IntegerField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('password', models.TextField(max_length=50, null=True)),
                ('rePassword', models.TextField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Login',
        ),
    ]
