# Generated by Django 3.2.5 on 2021-07-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20210730_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
