# Generated by Django 3.2.5 on 2021-07-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20210730_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.register'),
        ),
    ]
