# Generated by Django 3.2.5 on 2021-07-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210731_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='price',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
