# Generated by Django 3.2.5 on 2021-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='price',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
