# Generated by Django 4.2.19 on 2025-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_category_name_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='urlImage',
            field=models.URLField(null=1),
            preserve_default=1,
        ),
    ]
