# Generated by Django 4.2.19 on 2025-03-06 15:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_item_urlimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='ecommerce'),
        ),
    ]
