# Generated by Django 4.2.19 on 2025-03-06 15:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='urlImage',
            field=models.URLField(null=1, verbose_name='url image'),
        ),
    ]
