# Generated by Django 4.2.19 on 2025-08-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorie'},
        ),
        migrations.AddField(
            model_name='category',
            name='image_Url',
            field=models.URLField(null=1),
            preserve_default=1,
        ),
    ]
