# Generated by Django 4.2.19 on 2025-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_category_options_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_Url',
            field=models.URLField(blank=True, null=1),
        ),
    ]
